spring:
  application:
    name: Notebook REST
# Descomentar para utilizar postgresql en vez de H2
#  datasource:
#    host: localhost
#    port: 5432
#    database: asi
#    username: postgres
#    password: postgres
#    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
properties:
  clientHost: http://localhost:1234
